### ISSUE TITLE
Market analysis -Tutorax

### ISSUE THREAD

**Issue by Bogdanpoda** [AgnesCroteau/SOEN342_Best_Team_Ever#1]

**Comment by AgnesCroteau** [comment]
Hey, what documentation have you been using specifically for market analysis ?  Going through tutorials, powerpoints, and market analysis does not seem to have any templates unless I'm blind.  Maybe I'm blind.  Thanks.

**Comment by Bogdanpoda** [comment]
UI did not really followed a template, just tried to figure out what feature des tutorax offer

**Comment by Bogdanpoda** [comment]
The only slide I could relate is in the elicitation techniques :
<img width="487" alt="image" src="https://user-images.githubusercontent.com/68243088/192162080-232fb750-5979-43e7-94b3-43d2d44655bf.png">

**Comment by Bogdanpoda** [comment]
but I think its a little too much for what we are asked to do

**Comment by AgnesCroteau** [comment]
Cool thanks!

**Comment by MatthewBeaulieu0** [comment]
The comparative study looks well done I would say closing the issue
