### ISSUE TITLE
MArket Analysis -- Success scolaire

### ISSUE THREAD

**Issue by Bogdanpoda** [AgnesCroteau/SOEN342_Best_Team_Ever#3]

**Comment by AgnesCroteau** [comment]
Should do a table for comparative study in respect to what we want to do.

Ex: 
Users...
o   Students/parent (you can have them separately)
Students can rent textbooks on our website  **(NOT in Succes Scolaire, blog or homemade guides). Etc**.

**Comment by AgnesCroteau** [comment]
I'm satisfied with what I did but would not mind another pair of eyes , please! :) Let me know

**Comment by MatthewBeaulieu0** [comment]
Looks good
