### ISSUE TITLE
Elicitation technique number 1

### ISSUE THREAD

**Issue by Bogdanpoda** [AgnesCroteau/SOEN342_Best_Team_Ever#4]

**Comment by kennyphan100** [comment]
Elicitation technique used: Brainstorming

Documented all the ideas in the shared Google Docs, where I wrote a proper description for each idea.

**Comment by zihao429** [comment]
great idea, the group sessions will definitely help

**Comment by kennyphan100** [comment]
Brainstorming is done. Closing this issue.
