### ISSUE TITLE
Elicitation technique number 2

### ISSUE THREAD

**Issue by Bogdanpoda** [AgnesCroteau/SOEN342_Best_Team_Ever#5]

**Comment by zihao429** [comment]
Artifact-driven elicitation technique: Background study

**Comment by zihao429** [comment]
Background study, prerequisite to another elicitation technique, interviews

**Comment by zihao429** [comment]
Hey, can someone review this document for the second elicitation technique?
[Elicitation technique #2.pdf](https://github.com/AgnesCroteau/SOEN342_Best_Team_Ever/files/9658882/Elicitation.technique.2.pdf)

**Comment by AgnesCroteau** [comment]
Hi, what are exactly your zones of doubt for this document?

**Comment by AgnesCroteau** [comment]
My take is that it looks like solid work, however, it would be good to ask TA tomorrow.

Maybe we could mention how non-existent the "system as-is" seems to us at the moment.... right... Heck, do I even know for sure what I'm trying to say here... Anyhow, TBD.

**Comment by zihao429** [comment]
I am not too sure if I need to talk in details about the comparative study in the background study.

**Comment by zihao429** [comment]
Background study/interview questions are done

**Comment by zihao429** [comment]
Closing issue
